version: '3.8'

services:
  llm-retrieval-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=AIzaSyCyLEILSjE96HexvyxwFw_S-aEvz8GQ3N
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
